# Generated by Django 2.2.1 on 2021-06-23 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='audit_trail_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_myfile_related_audit_trail_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_myfile_related_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
