# Generated by Django 2.2.1 on 2021-06-23 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20210623_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_myfile_related_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
