# Generated by Django 2.2.1 on 2021-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='created_by_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='myfile',
            name='updated_by_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='filepath',
            field=models.FileField(blank=True, max_length=15000, null=True, upload_to='files/myfile/'),
        ),
    ]
