# Generated by Django 2.2.1 on 2021-03-22 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('permanent_delete', models.BooleanField(default=False, help_text='This false deletes items from recycle bin')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('filepath', models.CharField(max_length=13000)),
                ('updated_by', models.CharField(blank=True, max_length=5000, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('audit_trail_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_myfile_related_audit_trail_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setup_myfile_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_file',
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
